### ISSUE TITLE
Make less-rails work with sprockets 3

### ISSUE THREAD

**Issue by waynehoover** [metaskills/less-rails#100]
less-rails doesn't work with the latest sprockets 3 beta. I have created a simple rails 4.2 app to demonstrate: https://github.com/waynehoover/semantic-less-sprockets-3

Simply run `bundle` then `rails s` and go to the root url to see the error. I stumbled upon this while trying to integrate less-rails-semantic_ui into my app with the latest sprockets 3 beta (https://github.com/maxd/less-rails-semantic_ui/issues/2). Not sure if its sprockets related or less-rails related, but sass-rails seems to work fine with sprockets-3.

**Comment by maxd** [comment]
Here is [backtrace](https://gist.github.com/maxd/9fa4937a5ef62a184090). Seems like Tilt interface [will be deprecated](https://github.com/sstephenson/sprockets/tree/master#processor-interface) in Sprockets 3.x and [removed in 4.x](https://github.com/sstephenson/sprockets/blob/master/lib/sprockets/legacy_tilt_processor.rb#L7). 

So, I think need to support new processor interface.

**Comment by bmulholland** [comment]
@maxd The backtrace isn't visible to me.

I just ran into this issue myself. Upgrading only sprockets to 3.0 breaks my app whenever I try to do an `asset_path` for a `.less` file. I did a lot of searching before finding this issue, so for search engines: The issue I ran into was an error of "undefined method `[]' for nil:NilClass" when upgrading to sprockets 3.

**Comment by vizo** [comment]
Same here ... finding it out after 3h.

**Comment by waynehoover** [comment]
Might be time to escalate this issue as sprockets 3 was just released a lot of people will be upgrading.

**Comment by cha55son** [comment]
+1 been debugging this for awhile. Sprockets 2.x requires tilt but sprockets 3.x does not. Less-rails [requires tilt here](https://github.com/metaskills/less-rails/blob/c9f2cb92a32825684f4ad6d448028e6388a4e683/lib/less/rails.rb#L8), yet is not required in the gemfile. It was by luck that less-rails worked previously.

I am using the following as a fix:

```ruby
# Gemfile
source 'https://rubygems.org'
gem 'rails', '4.1.1'
gem 'less-rails', '2.6.0'
# Require tilt supported with sprockets 2.x which is what less-rails was using.
gem 'tilt', '1.4.1'
```

**Comment by sporto** [comment]
+1 I just created a new rails 4.2 app, less-rails doesn't work

```
<%= stylesheet_link_tag 'application', media: 'all' %>
```

Throws:

```
undefined method `[]' for nil:NilClass
```

**Comment by bmulholland** [comment]
@cha55son I tried this out and found that adding tilt to my Gemfile did not fix the problem. I still get the same issue.

**Comment by cha55son** [comment]
To clarify my error was something like:

```
File not found -- tilt
```

and was being generated from https://github.com/metaskills/less-rails/blob/c9f2cb92a32825684f4ad6d448028e6388a4e683/lib/less/rails.rb#L8

**Comment by rtroxler** [comment]
+1, ended up locking sprockets to an older version after searching for several hours for a fix.

 Getting the same error as @sporto.

**Comment by mateuszgorniak** [comment]
The same for me, still working with older version of Sprockets.

**Comment by simi** [comment]
I have fix prepared in `sprockets3` branch. Can you please confirm it works for you? I'm going to release new version ASAP.

**Comment by bmulholland** [comment]
I can confirm that this new branch fixes the issue for me.

**Comment by simi** [comment]
New version is out (https://rubygems.org/gems/less-rails/versions/2.7.0). Yay!

**Comment by maxd** [comment]
:+1: Excelent!

**Comment by metaskills** [comment]
Indeed, well done!
