### ISSUE TITLE
+600mb memory per thread after add less-rails to Gemfile!

### ISSUE THREAD

**Issue by alexesDev** [metaskills/less-rails#102]
Rails 4.1.1
less-rails  2.7.0
ruby 2.1.5p273

I dont care, just know...
1 year...
10 threads...
600x10 6gb... rage :hammer: I hate old projects (that I support)

**Comment by maxd** [comment]
Try to investigate problem more detail before post such baseless issues.

**Comment by simi** [comment]
@alexesDev we would like to solve your issue, but we need more informations. Do you have steps how to reproduce this? Feel free to create custom repository on github with this problem.

And as @maxd wrote, take a breath or two before you're posting emotional issues.

**Comment by alexesDev** [comment]
```
rails new less_test && cd less_test && echo "gem 'less-rails'\ngem 'therubyracer'" >> Gemfile && bundle && rails s
```
After this, in other terminal...
```
ps -eo size,pid,user,command --sort -size | awk '{ hr=$1/1024 ; printf("%13.2f Mb ",hr) } { for ( x=4 ; x<=NF ; x++ ) { printf("%s ",$x) } print "" }' | grep ruby
```

I have...
```
693.26 Mb /home/alexes/.rvm/rubies/ruby-2.1.5/bin/ruby bin/rails s 
```

**Comment by metaskills** [comment]
Wow, very interesting. Perhaps this is an issue with `therubyracer`. Can you confirm by dropping less-rails from the Gemfile?

**Comment by alexesDev** [comment]
I know about therubyracer, but I do not have time to explore less-rails to know exactly how it uses therubyracer. In my project I just remove less-rails.

**Comment by metaskills** [comment]
> I know about therubyracer, but I do not have time to explore less-rails to know exactly how it uses therubyracer.

Nor did I ask you to. If you just removed "therubyracer" from your Gemfile and started Rails again - you would have the answer to your question and a more constructive outlet vs that passive aggressive response which no one really cares for.

**Comment by alexesDev** [comment]
First post written in a passive aggressive manner, but other... just normal answers with all an information that I can now provide. Sorry for my English.

**Comment by metaskills** [comment]
I understand and appreciate the reply. Cheers.

**Comment by alexesDev** [comment]
> If you just removed "therubyracer" from your Gemfile and started Rails again
```
[WARNING] Please install gem 'therubyracer' to use Less.
```

**Comment by metaskills** [comment]
Damn. Maybe, doing this and checking the process.

```
$ irb
> require 'therubyracer`
```

**Comment by alexesDev** [comment]
```
irb
require 'therubyracer'
```
```
        79.85 Mb irb
```

**Comment by metaskills** [comment]
Related Issues:

* https://github.com/cowboyd/therubyracer/issues/311
* https://github.com/cowboyd/therubyracer/issues/210

**Comment by alexesDev** [comment]
Perhaps need to add a temp note to less-rails readme.
