### ISSUE TITLE
Could not read gem less-2.6.0

### ISSUE THREAD

**Issue by avijit-mandal** [metaskills/less-rails#110]
while bundle install i am getting this error.

Bundler::GemspecError: Could not read gem at /home/avijit/.rvm/gems/ruby-2.2.2/cache/less-2.6.0.gem. It may be corrupted.
An error occurred while installing less (2.6.0), and Bundler cannot continue.
Make sure that `gem install less -v '2.6.0'` succeeds before bundling.

so i tried gem install less -v '2.6.0' and got this problem.

ERROR:  Error installing less:
	invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /home/avijit/.r

please suggest some solution to install gem less-rails

**Comment by simi** [comment]
1. it works for me, ensure you can install another gem
2. please open this problem in [less gem](https://github.com/cowboyd/less.rb) (this is less-rails)

**Comment by avijit-mandal** [comment]
sorry, and thank you.
it's been resolved. removing old cache done everything.
thank you for your quick reply.
