### ISSUE TITLE
can't import less.erb file with interpolated strings

### ISSUE THREAD

**Issue by stevenspiel** [metaskills/less-rails#121]
I'm on `rails 4.2.5` with `less-rails 2.7.1` and I'm having issues importing less.erb files. 

My manifest file:

`application.less`:

``` less
@import 'base';
@import 'layout';
@import 'module';
@import 'state';
@import 'theme.less.erb';

/*
 *= require_tree .
 *= require_self
 */
```

and `theme.less.erb` is 

``` erb
.ui.button {
  color: <%= @branding.primary_color %>
}
```

Without the `erb` interpolation, it does fine, but otherwise, it raises:

```
Unrecognised input
```

The `@branding` variable is being set in `application_controller.rb`:

``` rb
def render(*args)
  @branding = Branding.new(cookies, params)
  super
end
```

But the `erb` interpolation doesn't work even without the variable:

``` erb
.ui.button {
  color: <%= '#ffffff' %>
}
```

I'd really like to have some per-user basis branding that is compiled (and possibly cached) on the fly. What do you suggest?

**Comment by brendon** [comment]
Since the asset is compiled at a different time to your request (i.e. when deploying into production) it won't have access to your request. I've solved this problem by inlining some override CSS in a `<style>` tag in the head of the page.
