### ISSUE TITLE
Could we use other javascript runtime(e.g. mini_racer)?

### ISSUE THREAD

**Issue by Roger-Tong** [metaskills/less-rails#136]
Our project uses react_on_rails to take advantage of react server rendering.
It was proved that **mini_racer** is way faster than the **therubyracer**. https://github.com/shakacode/react_on_rails/issues/501
So could you provide us some other option such as **mini_racer** as the javascript engine?

**Comment by simi** [comment]
I'm not sure how that works, but we have no direct dependency on `therubyracer`.

https://github.com/metaskills/less-rails/blob/master/less-rails.gemspec

**Comment by Roger-Tong** [comment]
You're right. It seems the dependency is on Less gem.
