### ISSUE TITLE
Silence warnings

### ISSUE THREAD

**Issue by lloeki** [metaskills/less-rails#141]
When running tests on a project depending on less-rails some warnings are raised (see below).

This is because with a recent rake (>=11.0), ruby warnings are now on by default.

What do you think about fixing those warnings as well as running the test suite with `ruby -w` / `$VERBOSE = true` / `t.warning = true` ?

```
/Users/lloeki/.gem/ruby/2.3.4/gems/less-rails-2.8.0/lib/less/rails/template_handlers.rb:33: warning: `*' interpreted as argument prefix
/Users/lloeki/.gem/ruby/2.3.4/gems/less-rails-2.8.0/lib/less/rails/railtie.rb:15: warning: possibly useless use of :: in void context
```

**Comment by simi** [comment]
should by fixed by #141
