### ISSUE TITLE
less-rails 3.0.0 in Rails 4 project causing Asset logical path has no extension error on asset compilation

### ISSUE THREAD

**Issue by ShaneBoyer** [metaskills/less-rails#142]
After a bundle update moved less-rails from 2.8.0 to 3.0.0 asset compilation fails with the error trace below.  Pinning less-rails back to 2.8.0 results in successful asset compilation.  The change log doesn't indicate any breaking changes.  This is from a rails 4.2.x project.  The files in the logical path folder are less files (they have .less extensions).   Thanks!

rake aborted!
  Sprockets::ArgumentError: Asset logical path has no extension: css/appalachian/appalachian-colors
  /var/app/ondeck/vendor/bundle/gems/sprockets-2.12.4/lib/sprockets/asset.rb:36:in `initialize'
  /var/app/ondeck/vendor/bundle/gems/sprockets-2.12.4/lib/sprockets/bundled_asset.rb:14:in `initialize'
  /var/app/ondeck/vendor/bundle/gems/sprockets-2.12.4/lib/sprockets/base.rb:377:in `new'
  /var/app/ondeck/vendor/bundle/gems/sprockets-2.12.4/lib/sprockets/base.rb:377:in `build_asset'
  /var/app/ondeck/vendor/bundle/gems/sprockets-2.12.4/lib/sprockets/index.rb:94:in `block in build_asset'
  /var/app/ondeck/vendor/bundle/gems/sprockets-2.12.4/lib/sprockets/caching.rb:58:in `cache_asset'
  /var/app/ondeck/vendor/bundle/gems/sprockets-2.12.4/lib/sprockets/index.rb:93:in `build_asset'
  /var/app/ondeck/vendor/bundle/gems/sprockets-2.12.4/lib/sprockets/base.rb:287:in `find_asset'
  /var/app/ondeck/vendor/bundle/gems/sprockets-2.12.4/lib/sprockets/index.rb:61:in `find_asset'
  /var/app/ondeck/vendor/bundle/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:211:in `block in find_asset'
  /var/app/ondeck/vendor/bundle/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:257:in `benchmark'
  /var/app/ondeck/vendor/bundle/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:210:in `find_asset'
  /var/app/ondeck/vendor/bundle/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:119:in `block in compile'
  /var/app/ondeck/vendor/bundle/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:118:in `each'
  /var/app/ondeck/vendor/bundle/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:118:in `compile'
  /var/app/ondeck/vendor/bundle/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
  /var/app/ondeck/vendor/bundle/gems/sprockets-2.12.4/lib/rake/sprocketstask.rb:146:in `with_logger'
  /var/app/ondeck/vendor/bundle/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
  /var/app/ondeck/vendor/bundle/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
  /opt/rubies/ruby-2.1.10/bin/bundle:23:in `load'
  /opt/rubies/ruby-2.1.10/bin/bundle:23:in `<main>'

**Comment by ShaneBoyer** [comment]
We don't have one at the moment.  Will try to put one together over the next few days.

**Comment by ShaneBoyer** [comment]
We attempted to create a new rails 4.2.x project to demonstrate the issue and were unsuccessful.  It will be a while until we can untangle the dependencies to find the root cause.  For now we're stuck with pinning less-rails to 2.8.0 to keep our project operating.  Closing this issue for now.

**Comment by simi** [comment]
I'm really sorry @ShaneBoyer for this issue, but without reproducible state I can't solve it :( If you're really in trouble, feel free to ping me in my email (in my GH profile) and we can try to debug this privately.
