### ISSUE TITLE
rails s command issue

### ISSUE THREAD

**Issue by victorsosa** [metaskills/less-rails#149]
The rails s command is showing this issue bellow; this project use to run fine if you remove the less-rails gem; but I can't do it because there is a dependency on my project.

```
    [vns@betito perseus]$ rails s
    /usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = v8::Handle<v8::Value>; _Alloc = std::allocator<v8::Handle<v8::Value> >; std::vector<_Tp, _Alloc>::reference = v8::Handle<v8::Value>&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
    Aborted (core dumped)
```

My env:

Fedora 28
ruby 2.5.1
rails 5.2.0
libg++ 8.1.1

check out this:
https://stackoverflow.com/q/51661931/3159178

gem file:
```
.....
gem "therubyracer", platforms: :ruby
gem "less-rails"#, '2.7.1' #this broke rails s
gem 'twitter-bootstrap-rails', :git => 'git://github.com/seyhunak/twitter-bootstrap-rails.git'
```

**Comment by victorsosa** [comment]
I found the issue and it is related to 'therubyracer' lib
There is a bug with the use of vector out of bounds.

to this line:
[return &vector[0];](https://github.com/victorsosa/therubyracer/blob/56da5e54751feca3a1ae056001c8cc469fdd641e/ext/v8/rr.h#L223)

on file: ext/v8/rr.h#L223

so this is not related to this library.

**Comment by simi** [comment]
Thanks fo reporting back.
