### ISSUE TITLE
Asset path does not work when application is at a subdirectory

### ISSUE THREAD

**Issue by JohnColvin** [metaskills/less-rails#25]
If an app is at a subdirectory, the url created for an asset does not include the subdirectory.

ex: 

actual path:         http://domain.com/sub/assets/twitter/bootstrap/glyphicons-halflings-white-4fbb6a0b9b4e61912f486ac494a858f1.png
generated path: http://domain.com/assets/twitter/bootstrap/glyphicons-halflings-white-4fbb6a0b9b4e61912f486ac494a858f1.png

**Comment by jrochkind** [comment]
If anyone is reading this 3 years later, my preferred way to do this is to compile with:

    RAILS_RELATIVE_URL_ROOT=/sub_uri bundle exec rake assets:precompile

No need to do change any config in your app source if you do it this way; I prefer not to hard-code the sub-uri into my source, but have that be a deployment-time configuration.
