### ISSUE TITLE
Recompile imported .less files after modification

### ISSUE THREAD

**Issue by mattiasarro** [metaskills/less-rails#46]
**Update:**

I have an application.less file that @imports various .less files, (e.g. sites.less and chart.less) from assets/stylesheets. When I edit chart.less and refresh application.css, the changes in chart.less are reflected in the compiled CSS file, but this was not the case for sites.less. This led me to a false conclusion that adding `config.less.env = 'development'` to an environment file fixed my issue, when I was actually testing on the chart.less file that was refreshing properly anyway.

My actual issue was omitting the `//= depend_on "sites.less"` statement. Though I did not have a depend_on charts.less statement either, which led me to weird false conclusions. @import should have added the depend_on in the background, but for some imports it did not.

**The old suggestion below is rubbish:**

I think it's worth pointing out (perhaps under "Import Hooks" in the readme?) that the contents of @import'ed .less files will be cached. To make sure your imported files are recompiled after they have been modified, tell LESS that we're in development mode via `config/environments/development.rb`:

``` Ruby
config.less.env = 'development';
```

**Comment by tjwudi** [comment]
Any update? +1 for no workaround working.

**Comment by maxd** [comment]
Seems like this issue has been fixed in #88. Do you have this problem with latest version of less-rails?

**Comment by tjwudi** [comment]
According to `Gemfile`, I am using `less-rails (2.6.0)`.

**Comment by maxd** [comment]
@tjwudi Try to do the following steps:

1. Close app
1. Reset cache use `rake tmp:clear`

If it doesn't works then try to update `sprockets-rails` gem use `bundle update sprockets-rails` command and retry steps above.

**Comment by tjwudi** [comment]
@maxd Thank your for your advise. I solved that by changing the importing .less files. If I encounter this problem again, I will use your solutions. Thanks again!

**Comment by th3m4ri0** [comment]
I confirm the issue is fixed. I updated less-rails (```bundle update less-rails```) from 2.5.0 to 2.6.0, now editing non-root files trigger the recompile :+1:

**Comment by eveevans** [comment]
I'm using less-rails 2.7.1 and still have the problem :/
