### ISSUE TITLE
Less-rails using lessc --relative-urls by default

### ISSUE THREAD

**Issue by pettomartino** [metaskills/less-rails#94]
Hi,
How Can I remove the "--relative-urls" config in less-rails? - http://lesscss.org/usage/#command-line-usage-relative-urls

In less by default this option is disabled, but in 'less-rails' when I call url() css function its produce a relative url.

For example:
app/assets/stylesheets/template/settings.less
@my-background = asset-path('my-image.png');
app/assets/stylesheets/template/header.less 
background-image: url(@my-background)

this will output the following:
background-image: url(template/"/assets/my-image.png");

**Comment by ilyapoz** [comment]
up, I'm stuck with the same issue too. Can anybody look into it? @metaskills ?

**Comment by ilyapoz** [comment]
oh ok I see, there's no way as of now.
I will try and make in improvement here.
