### ISSUE TITLE
Update to version of LESS.rb which uses LESS 2.X

### ISSUE THREAD

**Issue by bjankord** [metaskills/less-rails#98]
Would like to be able to use less-rails with LESS 2.X. Knowing this is blocked on less.rb updating the compiler it uses, I added an [issue](https://github.com/cowboyd/less.rb/issues/77) on that repo as well.

**Comment by tBaxter** [comment]
+1

**Comment by tBaxter** [comment]
Any movement?

**Comment by tBaxter** [comment]
Anything? Anything at all?

**Comment by simi** [comment]
https://github.com/metaskills/less-rails/issues/98#issuecomment-96666389 this is upstream issue. Let's move there.

**Comment by tBaxter** [comment]
Upstream where? Link?

**Comment by simi** [comment]
sorry, bad link - https://github.com/cowboyd/less.rb/pull/79
