### ISSUE TITLE
Issues with asset-url or image-url and svg

### ISSUE THREAD

**Issue by AntiFish03** [metaskills/less-rails#99]
I am just now converting from manually compiled less to less-rails and svgs paths were working before.

The error I am seeing is:
```
error evaluating function `data-uri`: Optional dependency "mime" is required for .svg
```
as an example it is having issues with this line

```less
background-image: ~"asset-url(@{flag-icon-css-path}/@{country}.svg)";
```

it also has the same issue with:
```less
background-image: asset-url("@{flag-icon-css-path}/@{country}.svg");
```

**Comment by maxd** [comment]
@AntiFish03 Could you please provide simple project to reproduce problem?

**Comment by AntiFish03** [comment]
Sure give me a few

**Comment by AntiFish03** [comment]
Ignore me... it was a short between the back of the chair and the keyboard.

**Comment by AntiFish03** [comment]
I found the issue while setting up the demo for you

**Comment by awh-tokyo** [comment]
Well what was the issue?

**Comment by AntiFish03** [comment]
@awh-tokyo, Sorry I don't remember that was over 3 years ago.
